fix: prometheus metric naming and typing
twitter/rpc-perf pull request #317
Opened 2021-06-26 17:39 UTC by bruuuuuuuce

**Problem**
There are 2 issues:
- Some prometheus metrics collectors (ex. [open telemetry](https://github.com/open-telemetry/opentelemetry-collector/issues/3118)) don't support untyped prometheus metrics. Per the [prometheus spec](https://prometheus.io/docs/instrumenting/exposition_formats/#line-format), an optional metric `TYPE` can be added to each metric. Open telemetry requires this to process metrics
- [Prometheus](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) requires metric names to match this regex `[a-zA-Z_:][a-zA-Z0-9_:]*`, so metrics such as `responses_latency_p99.99` are actually invalid due to the `.` Using open telemetry, it won't process any of the metrics if one of the metrics is of invalid format.

**Solution**

I have changed the metric format to be
```
# TYPE {metric_name} gauge
{metric_name} {metric_value}
```
and removed the `.` from all metric names. So `responses_latency_p99.99` becomes `responses_latency_p9999`.

**Result**

The open telemetry collector can process and understand the prometheus metrics emitted from `rpc-perf`

2021-06-26 17:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twitter/rpc-perf?pullRequest=317) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/twitter/rpc-perf?pullRequest=317) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twitter/rpc-perf?pullRequest=317) it.</sub>

2021-06-29 15:20 UTC, brayniac requested changes
Thanks for opening this PR. I think there might be deeper fixes that need to be made to expose true type annotations, but I think with a few changes this could be a good stop-gap fix.

2021-06-29 15:20 UTC, brayniac commented on .gitignore
> +.idea
I feel like IDE/editor specific ignores should be in your top-level ~/.gitconfig and not in this repo.

2021-06-29 15:20 UTC, brayniac commented on src/stats/snapshot.rs
> +                        data.push(format!("# TYPE {} gauge\n{} {}", metric_name, metric_name, value));
Is there a downside to always marking the metric as a 'gauge' type here? Some of these are counters.

2021-06-29 15:20 UTC, brayniac commented on src/stats/snapshot.rs
> +                    let metric_name = format!("{}/p{:02}", label, percentile).replace(".","");
Maybe it'd be better to use a 'percentile' label so we can keep the decimal point. I've found it's a little clearer particularly when a pXX notation might be ambiguous.

2021-06-30 04:42 UTC, bruuuuuuuce commented on .gitignore
> +.idea
I actually didn't know that you could add a gitignore inside of the git config, thanks for the info!

2021-06-30 04:54 UTC, bruuuuuuuce commented on src/stats/snapshot.rs
> +                        data.push(format!("# TYPE {} gauge\n{} {}", metric_name, metric_name, value));
In prometheus, `counters` are monotomically increasing numbers. So I think there are special ways that you can query then, such as using the `rate` function to query the change in rate of a specific metric. I am not too familiar with the prometheus specs, but this is my understand. I chose the `gauge` metric because 
- I was looking for a quick fix to unblock my from querying metrics using open-telemetry
- a `gauge` __can__ be used as a `counter`, while the opposite is not true

For a more holistic solution, we would probably need to add an additional property to the metrics, in addition to `statistic` and `name`, lets call it `type`, which we would be able to use in the formatted string. Something like
 ```
 let label = metric.statistic().name();
 let output = metric.output();
 let type = metric.type();
 data.push(format!("# TYPE {} {}\n{} {}", metric_name, type, metric_name, value));
 ```
 I wasnt sure where to add this, so I went the other route and just defaulted everything to a `gauge`

2021-06-30 05:05 UTC, bruuuuuuuce commented on src/stats/snapshot.rs
> +                    let metric_name = format!("{}/p{:02}", label, percentile).replace(".","");
I like that idea, but [prometheus-labels](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) also have to match the regex `[a-zA-Z_:][a-zA-Z0-9_:]*`, so I don't think that it will be supported. But I will try it and post back here my findings.

2021-06-30 15:34 UTC, brayniac commented on src/stats/snapshot.rs
> +                        data.push(format!("# TYPE {} gauge\n{} {}", metric_name, metric_name, value));
Makes sense. This works for now

2021-06-30 15:37 UTC, brayniac commented on src/stats/snapshot.rs
> +                    let metric_name = format!("{}/p{:02}", label, percentile).replace(".","");
My understanding is that the restriction applies only to the label name, not the value. My proposal would be to have the metrics be in the form of: `response_latency{percentile="99.9"}` which appears like it would be valid. I could be wrong though.

2021-07-01 20:31 UTC, bruuuuuuuce commented on src/stats/snapshot.rs
> +                    let metric_name = format!("{}/p{:02}", label, percentile).replace(".","");
I ran a test using open telemetry with the metric names like `response_latency{percentile="99.9"}`, and it was still failing to process them, saying that the prometheus metrics are invalid. I double checked the prometheus docks and found this 
```
Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*. Label names beginning with __ are reserved for internal use.
```
so I think that, unfortunately, the label names are also restricted

2021-07-01 21:06 UTC, brayniac commented on src/stats/snapshot.rs
> +                    let metric_name = format!("{}/p{:02}", label, percentile).replace(".","");
Unless I'm missing something, they use floating point values in examples - for example: https://prometheus.io/docs/practices/histograms/#quantiles shows using a query like:

```avg(http_request_duration_seconds{quantile="0.95"}) // BAD!```

And the summary metric type seems to imply we can export quantiles from a in-process summarization of the distribution. 

https://prometheus.io/docs/concepts/metric_types/#summary

And in the Prometheus exposition format docs https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#comments-help-text-and-type-information

It implies that the "99.9" is actually called a 'label value' not a label name, which would mean that the following criteria apply: ```label_value can be any sequence of UTF-8 characters, but the backslash (\), double-quote ("), and line feed (\n) characters have to be escaped as \\, \", and \n, respectively.```

Can you test with actual prometheus instead of opentelemetry? I won't have time to test this myself for some time. I really feel we need a better solution than what's proposed in the PR right now.

2021-07-01 23:11 UTC, bruuuuuuuce commented on src/stats/snapshot.rs
> +                    let metric_name = format!("{}/p{:02}", label, percentile).replace(".","");
@brayniac you are right, I tested with both prometheus as well as open telemetry, and the labels work with both. In my earlier testing, it wasn't working because I had formatted the metric_labels incorrectly. Thanks for pointing this out. The stats now come through looking like 
```
Metric #5
Descriptor:
     -> Name: responses_latency
     -> Description:
     -> Unit:
     -> DataType: DoubleGauge
DoubleDataPoints #0
Data point labels:
     -> percentile: 50
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2021-07-01 23:05:16.719 +0000 UTC
Value: 2579999.000000
DoubleDataPoints #1
Data point labels:
     -> percentile: 75
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2021-07-01 23:05:16.719 +0000 UTC
Value: 3329999.000000
DoubleDataPoints #2
Data point labels:
     -> percentile: 90
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2021-07-01 23:05:16.719 +0000 UTC
Value: 4019999.000000
DoubleDataPoints #3
Data point labels:
     -> percentile: 99
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2021-07-01 23:05:16.719 +0000 UTC
Value: 7949999.000000
DoubleDataPoints #4
Data point labels:
     -> percentile: 99.9
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2021-07-01 23:05:16.719 +0000 UTC
Value: 19199999.000000
DoubleDataPoints #5
Data point labels:
     -> percentile: 99.99
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2021-07-01 23:05:16.719 +0000 UTC
Value: 19199999.000000
```

2021-07-01 23:46 UTC, brayniac commented on src/stats/snapshot.rs
> +                    let metric_name = format!("{}/p{:02}", label, percentile).replace(".","");
Beautiful! This seems like a better way to do this anyway from a dashboard perspective.

2021-07-01 23:48 UTC, brayniac requested changes

2021-07-01 23:48 UTC, brayniac commented on src/stats/snapshot.rs
> +                    // per prometheus naming https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels metric names cannot have . in them
This comment can be removed now?

2021-07-02 00:09 UTC, brayniac approved these changes
Looks good. Thanks for working through the feedback.

Will merge tomorrow if CI run is successful.

2021-07-02 18:02 UTC, merged