Add cardinality to U32 key/value configs
twitter/rpc-perf pull request #376
Opened 2022-09-28 15:55 UTC by aetimmes

Problem

The cardinality of the keyspace being constant (in the case of the U32 field type) or tied directly to the 52^N of the keyspace length (in the case of the Alphanumeric field type) makes it difficult to control the exact size of the keyspace:

len1: 52
len2: 2,704
len3: 140,608
len4: 7,311,616
len5: 380,204,032
len6: 19,770,609,664

 The wide gaps between these keyspace cardinalities make it difficult to design load test configurations that achieve a specific hit-rate.

Solution

This PR implements the "cardinality" config option for key/innerkey/value spaces for U32 field types which constrains the range of the random number generator used to generate these fields.

Result

See above.

It's worth noting that serde only seems to want to accept functions for defaults, and not literals, so I used u32.max_value() for the default for this field, even though the Rust docs list that function as deprecated (it's being replaced by the u32::MAX constant, which serde doesn't accept). If there's a better way to handle this, let me know.

2022-09-28 21:56 UTC, brayniac commented on .gitignore
> +*.swp
Please add these to your local git config ignores and not to the project. We don't want to maintain entries for every possible editor.

2022-09-29 02:07 UTC, brayniac requested changes
It would be nice to address this for alphanumeric value types as well, but this PR addresses a current need and I would be willing to merge after cleanup per my other comments. Please open an issue to track adding similar functionality for alphanumeric types. We might consider implementing it using some base conversion into a known keyspace (eg base 10 rng -> base 52 representation using the defined alphanumeric keyspace and padding it accordingly to the correct width). 

Thanks for adding this functionality and contributing to the project!

2022-09-29 02:07 UTC, brayniac commented on src/config_file.rs
> +    #[serde(default = "u32::max_value")]
Consider defining our own function that just returns the default value using the associated constant instead of this function.

2022-09-29 02:28 UTC, aetimmes commented
https://github.com/twitter/rpc-perf/issues/377 opened.

2022-09-29 03:24 UTC, aetimmes commented
CI is passing and I believe all concerns are addressed. I can squash/force-push this branch so as not to litter the commit history if you'd like.

2022-09-29 13:26 UTC, aetimmes commented on src/config_file.rs
> +    #[serde(default = "u32::max_value")]
Addressed in https://github.com/twitter/rpc-perf/pull/376/commits/86e31928062ea7d1103f070c00bc7fd3bdef2430

2022-09-29 13:26 UTC, aetimmes commented on src/config.rs
> +    //#TODO(atimmes): implement cardinality for Alphanumeric fields
Addressed in https://github.com/twitter/rpc-perf/pull/376/commits/88105724b8c4dfbc31c4c3096bf30cb4045759f5

2022-09-29 13:27 UTC, aetimmes commented on configs/memcache_zookeeper.toml
> +# the length of the key in bytes, for alphanumeric fields, the keyspace will# be: 52^N keys
Addressed in https://github.com/twitter/rpc-perf/pull/376/commits/f88c568c8e4a9f407b3da8a153ea3f6e3cb59fad

2022-09-29 17:35 UTC, brayniac approved these changes

2022-09-29 17:47 UTC, merged